import type { Product, Category, Review } from "@/types";

export const mockCategories: Category[] = [
  {
    id: "1",
    name: "Men",
    slug: "men",
    imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Women",
    slug: "women",
    imageUrl: "https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=600&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Accessories",
    slug: "accessories",
    imageUrl: "https://images.unsplash.com/photo-1553545985-1e0d8781d5db?w=600&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Collections",
    slug: "collections",
    imageUrl: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockReviews: Review[] = [
  {
    id: "r1",
    productId: "1",
    authorName: "Arjun M.",
    authorCity: "Mumbai",
    rating: 5,
    comment:
      "The quality is unmatched. The AeroFlex Jacket has become my go-to for every outdoor adventure.",
    verified: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "r2",
    productId: "2",
    authorName: "Priya S.",
    authorCity: "Delhi",
    rating: 5,
    comment:
      "Finally, activewear that performs as well as it looks. Worth every rupee.",
    verified: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "r3",
    productId: "3",
    authorName: "Karan D.",
    authorCity: "Bangalore",
    rating: 5,
    comment:
      "The ThermoShield technology is incredible. Stays warm without the bulk.",
    verified: true,
    createdAt: new Date().toISOString(),
  },
];

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "AeroFlex Performance Hoodie",
    slug: "aeroflex-performance-hoodie",
    description:
      "Advanced 4-way stretch fabric with ThermoShield technology. Engineered for peak performance in any condition.",
    price: 3499,
    comparePrice: 4399,
    images: [
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80",
      "https://images.unsplash.com/photo-1605296867304-46d5465a13f1?w=800&q=80",
    ],
    categoryId: "1",
    category: mockCategories[0],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Charcoal", hex: "#4a4a4a" },
      { name: "Red", hex: "#ef4444" },
      { name: "White", hex: "#ffffff" },
    ],
    stock: 50,
    isBestseller: true,
    isNewArrival: false,
    isFeatured: true,
    tags: ["hoodie", "men", "performance"],
    avgRating: 4.8,
    reviewCount: 234,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Summit Training Tee",
    slug: "summit-training-tee",
    description:
      "Ultra-lightweight moisture-wicking tee. Perfect for intense training sessions and outdoor activities.",
    price: 1299,
    comparePrice: 1499,
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80",
      "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=800&q=80",
    ],
    categoryId: "1",
    category: mockCategories[0],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "White", hex: "#ffffff" },
      { name: "Red", hex: "#ef4444" },
    ],
    stock: 100,
    isBestseller: true,
    isNewArrival: false,
    isFeatured: false,
    tags: ["tee", "men", "training"],
    avgRating: 4.7,
    reviewCount: 169,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Apex Compression Joggers",
    slug: "apex-compression-joggers",
    description:
      "Engineered compression fit for maximum muscle support. Moisture-wicking and quick-dry technology.",
    price: 2799,
    comparePrice: 3469,
    images: [
      "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&q=80",
      "https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=800&q=80",
    ],
    categoryId: "1",
    category: mockCategories[0],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Charcoal", hex: "#4a4a4a" },
    ],
    stock: 75,
    isBestseller: true,
    isNewArrival: false,
    isFeatured: true,
    tags: ["joggers", "men", "compression"],
    avgRating: 4.9,
    reviewCount: 412,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "ThermoShield Training Jacket",
    slug: "thermoshield-training-jacket",
    description:
      "ThermoShield insulation keeps you warm during cold-weather training. Lightweight, packable design.",
    price: 4999,
    comparePrice: 6599,
    images: [
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80",
      "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&q=80",
    ],
    categoryId: "1",
    category: mockCategories[0],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Charcoal", hex: "#4a4a4a" },
      { name: "Red", hex: "#ef4444" },
    ],
    stock: 30,
    isBestseller: true,
    isNewArrival: false,
    isFeatured: true,
    tags: ["jacket", "men", "thermoshield"],
    avgRating: 4.9,
    reviewCount: 156,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Velocity Training Tank",
    slug: "velocity-training-tank",
    description:
      "Breathable mesh panels and moisture-control technology for intense workouts.",
    price: 999,
    comparePrice: 1249,
    images: [
      "https://images.unsplash.com/photo-1604480132736-44c188fe4d20?w=800&q=80",
    ],
    categoryId: "1",
    category: mockCategories[0],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Red", hex: "#ef4444" },
    ],
    stock: 60,
    isBestseller: false,
    isNewArrival: true,
    isFeatured: false,
    tags: ["tank", "men", "training"],
    avgRating: 4.6,
    reviewCount: 89,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "6",
    name: "FlexForm Sports Bra",
    slug: "flexform-sports-bra",
    description:
      "Medium-impact support with flexible underwire. Perfect for yoga, pilates, and light training.",
    price: 1799,
    comparePrice: 2199,
    images: [
      "https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=800&q=80",
    ],
    categoryId: "2",
    category: mockCategories[1],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "White", hex: "#ffffff" },
      { name: "Red", hex: "#ef4444" },
    ],
    stock: 45,
    isBestseller: false,
    isNewArrival: true,
    isFeatured: true,
    tags: ["sports-bra", "women", "yoga"],
    avgRating: 4.8,
    reviewCount: 203,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "7",
    name: "Sculpt High-Waist Leggings",
    slug: "sculpt-high-waist-leggings",
    description:
      "Squat-proof, 4-way stretch leggings with a flattering high-waist band and hidden pocket.",
    price: 2499,
    comparePrice: 2999,
    images: [
      "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&q=80",
    ],
    categoryId: "2",
    category: mockCategories[1],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Charcoal", hex: "#4a4a4a" },
    ],
    stock: 55,
    isBestseller: false,
    isNewArrival: true,
    isFeatured: false,
    tags: ["leggings", "women", "yoga"],
    avgRating: 4.9,
    reviewCount: 318,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "8",
    name: "PowerLift Training Gloves",
    slug: "powerlift-training-gloves",
    description:
      "Full palm protection with wrist support. Breathable mesh back keeps hands cool.",
    price: 899,
    comparePrice: 1099,
    images: [
      "https://images.unsplash.com/photo-1553545985-1e0d8781d5db?w=800&q=80",
    ],
    categoryId: "3",
    category: mockCategories[2],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Red", hex: "#ef4444" },
    ],
    stock: 80,
    isBestseller: false,
    isNewArrival: false,
    isFeatured: false,
    tags: ["gloves", "accessories"],
    avgRating: 4.5,
    reviewCount: 127,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Performance Gear - Men
export const performanceGearProducts: Product[] = [
  {
    id: "perf-1",
    name: "Raglan T",
    slug: "raglan-t",
    description: "4-Way Stretch. Odour Resistant. Ultra-breathable performance tee engineered for intense workouts.",
    price: 1199,
    comparePrice: 1499,
    images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80"],
    categoryId: "1",
    category: mockCategories[0],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "White", hex: "#ffffff" },
      { name: "Black", hex: "#1a1a1a" },
      { name: "Grey", hex: "#808080" },
    ],
    stock: 120,
    isBestseller: true,
    isNewArrival: false,
    isFeatured: true,
    tags: ["raglan-t", "men", "performance", "tee"],
    avgRating: 4.7,
    reviewCount: 142,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "perf-2",
    name: "Lightweight Short",
    slug: "lightweight-short",
    description: "Ultra-Light. Functional Pocketing. Maximum mobility for training and running.",
    price: 1599,
    comparePrice: 1999,
    images: ["https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800&q=80"],
    categoryId: "1",
    category: mockCategories[0],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Navy", hex: "#1e3a8a" },
      { name: "Grey", hex: "#808080" },
    ],
    stock: 95,
    isBestseller: false,
    isNewArrival: true,
    isFeatured: false,
    tags: ["lightweight-short", "men", "performance", "shorts"],
    avgRating: 4.6,
    reviewCount: 89,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "perf-3",
    name: "Performance Short",
    slug: "performance-short",
    description: "Durable. 4-Way Stretch. Built for high-intensity training and outdoor activities.",
    price: 1899,
    comparePrice: 2399,
    images: ["https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800&q=80"],
    categoryId: "1",
    category: mockCategories[0],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Grey", hex: "#808080" },
    ],
    stock: 80,
    isBestseller: true,
    isNewArrival: false,
    isFeatured: true,
    tags: ["performance-short", "men", "performance", "shorts"],
    avgRating: 4.8,
    reviewCount: 216,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "perf-4",
    name: "Oversize Tee",
    slug: "oversize-tee",
    description: "Breathable. 4-Way Stretch. Relaxed fit with performance fabric technology.",
    price: 1299,
    comparePrice: 1599,
    images: ["https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80"],
    categoryId: "1",
    category: mockCategories[0],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Charcoal", hex: "#4a4a4a" },
      { name: "White", hex: "#ffffff" },
    ],
    stock: 110,
    isBestseller: false,
    isNewArrival: true,
    isFeatured: false,
    tags: ["oversize-tee", "men", "performance", "tee"],
    avgRating: 4.5,
    reviewCount: 78,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "perf-5",
    name: "Muscle Tank",
    slug: "muscle-tank",
    description: "Natural Fiber. Relaxed Fit. Show off your gains with breathable muscle tank.",
    price: 999,
    comparePrice: 1299,
    images: ["https://images.unsplash.com/photo-1604480132736-44c188fe4d20?w=800&q=80"],
    categoryId: "1",
    category: mockCategories[0],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Grey", hex: "#808080" },
      { name: "Olive", hex: "#556b2f" },
    ],
    stock: 75,
    isBestseller: false,
    isNewArrival: false,
    isFeatured: false,
    tags: ["muscle-tank", "men", "performance", "tank"],
    avgRating: 4.4,
    reviewCount: 63,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "perf-6",
    name: "¼ Zip L/S",
    slug: "quarter-zip-ls",
    description: "4-Way Stretch. Breathable. Perfect layering piece for training and outdoor activities.",
    price: 2199,
    comparePrice: 2699,
    images: ["https://images.unsplash.com/photo-1620799140188-3b2a7ade2e0b?w=800&q=80"],
    categoryId: "1",
    category: mockCategories[0],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Grey", hex: "#808080" },
      { name: "Navy", hex: "#1e3a8a" },
    ],
    stock: 65,
    isBestseller: true,
    isNewArrival: false,
    isFeatured: true,
    tags: ["quarter-zip", "men", "performance", "long-sleeve"],
    avgRating: 4.9,
    reviewCount: 187,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Lifestyle Gear - Men
export const lifestyleGearProducts: Product[] = [
  {
    id: "life-1",
    name: "Tech Hoodie",
    slug: "tech-hoodie",
    description: "4-Way Stretch. Lightweight. Premium tech hoodie for gym-to-street transition.",
    price: 3299,
    comparePrice: 3999,
    images: ["https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=800&q=80"],
    categoryId: "1",
    category: mockCategories[0],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Charcoal", hex: "#4a4a4a" },
    ],
    stock: 55,
    isBestseller: true,
    isNewArrival: true,
    isFeatured: true,
    tags: ["tech-hoodie", "men", "lifestyle", "hoodie"],
    avgRating: 4.9,
    reviewCount: 298,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "life-2",
    name: "Performance Pant",
    slug: "performance-pant",
    description: "Lightweight. 4-Way Stretch. Versatile performance joggers for training and lifestyle.",
    price: 2899,
    comparePrice: 3599,
    images: ["https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&q=80"],
    categoryId: "1",
    category: mockCategories[0],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Charcoal", hex: "#4a4a4a" },
      { name: "Navy", hex: "#1e3a8a" },
    ],
    stock: 70,
    isBestseller: true,
    isNewArrival: false,
    isFeatured: true,
    tags: ["performance-pant", "men", "lifestyle", "joggers"],
    avgRating: 4.8,
    reviewCount: 245,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "life-3",
    name: "Performance Jacket",
    slug: "performance-jacket",
    description: "Lightweight. 4-Way Stretch. Technical jacket for all-weather performance.",
    price: 4499,
    comparePrice: 5499,
    images: ["https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&q=80"],
    categoryId: "1",
    category: mockCategories[0],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Charcoal", hex: "#4a4a4a" },
    ],
    stock: 45,
    isBestseller: true,
    isNewArrival: true,
    isFeatured: true,
    tags: ["performance-jacket", "men", "lifestyle", "jacket"],
    avgRating: 4.9,
    reviewCount: 312,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Compression - Men
export const compressionProducts: Product[] = [
  {
    id: "comp-1",
    name: "Compression Tee",
    slug: "compression-tee",
    description: "Engineered compression fit for maximum muscle support. Moisture-wicking technology.",
    price: 1699,
    comparePrice: 2099,
    images: ["https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80"],
    categoryId: "1",
    category: mockCategories[0],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "White", hex: "#ffffff" },
      { name: "Grey", hex: "#808080" },
    ],
    stock: 90,
    isBestseller: true,
    isNewArrival: false,
    isFeatured: true,
    tags: ["compression-tee", "men", "compression"],
    avgRating: 4.7,
    reviewCount: 156,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "comp-2",
    name: "Compression Shorts",
    slug: "compression-shorts",
    description: "High-performance compression shorts for training. Reduce muscle fatigue.",
    price: 1899,
    comparePrice: 2299,
    images: ["https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800&q=80"],
    categoryId: "1",
    category: mockCategories[0],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Navy", hex: "#1e3a8a" },
    ],
    stock: 85,
    isBestseller: true,
    isNewArrival: false,
    isFeatured: true,
    tags: ["compression-shorts", "men", "compression"],
    avgRating: 4.8,
    reviewCount: 203,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "comp-3",
    name: "Compression Tights",
    slug: "compression-tights",
    description: "Full-length compression tights. Maximum support for intense training sessions.",
    price: 2299,
    comparePrice: 2799,
    images: ["https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&q=80"],
    categoryId: "1",
    category: mockCategories[0],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Charcoal", hex: "#4a4a4a" },
    ],
    stock: 75,
    isBestseller: true,
    isNewArrival: false,
    isFeatured: true,
    tags: ["compression-tights", "men", "compression"],
    avgRating: 4.9,
    reviewCount: 287,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "comp-4",
    name: "Compression Top",
    slug: "compression-top",
    description: "Long-sleeve compression top with strategic ventilation. Enhanced performance.",
    price: 1999,
    comparePrice: 2499,
    images: ["https://images.unsplash.com/photo-1620799140188-3b2a7ade2e0b?w=800&q=80"],
    categoryId: "1",
    category: mockCategories[0],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "White", hex: "#ffffff" },
      { name: "Red", hex: "#ef4444" },
    ],
    stock: 80,
    isBestseller: false,
    isNewArrival: true,
    isFeatured: false,
    tags: ["compression-tops", "men", "compression"],
    avgRating: 4.7,
    reviewCount: 134,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Merge all men's products
export const allMenProducts = [
  ...mockProducts.filter(p => p.categoryId === "1"),
  ...performanceGearProducts,
  ...lifestyleGearProducts,
  ...compressionProducts,
];
